### ISSUE TITLE
DSBN

### ISSUE THREAD

**Issue by xiaobenniao1** [Eureka-JTX/Super-Resolution#1]
你好，DSBN代码在你自己的代码中添加成功了吗

**Comment by Eureka-JTX** [comment]
啊？DSBN应该是DA的内容吧，你能给我指出之前的回复吗，谢谢

**Comment by xiaobenniao1** [comment]
https://github.com/wgchang/DSBN/issues/11这篇文章我看您可能使用了，所以问问您运用到自己代码中了吗

**Comment by Eureka-JTX** [comment]
尽管没有复现出论文中的水平，当时我还是在DSBN上加入自己的设计做过一些实验，但最后还是不了了之了。最近我也不再做DA相关的问题了，很抱歉~
